
export const ProductName = [
    { Id: 1, pname: 'Breakfast' },
    { Id: 2, pname: 'Lunch' },
    { Id: 3, pname: 'Dinner' },
    { Id: 4, pname: 'Snakes' },
    { Id: 5, pname: 'Travelling' },
    { Id: 6, pname: 'Recharge' },
    { Id: 7, pname: 'Other' },
    { Id: 8, pname: 'Casual' },
    { Id: 9, pname: 'Cloth' },
    { Id: 10, pname: 'Juice' },
    { Id: 11, pname: 'PG Rent +' },
    // {Id:11,pname:'Breakfast'},
    // {Id:12,pname:'Breakfast'},
    // {Id:13,pname:'Breakfast'},
  ];
export const ProductNameString = [
    { Id: 'Breakfast', pname: 'Breakfast' },
    { Id: 'Lunch', pname: 'Lunch' },
    { Id: 'Dinner', pname: 'Dinner' },
    { Id: 'Snakes', pname: 'Snakes' },
    { Id: 'Travelling', pname: 'Travelling' },
    { Id: 'Recharge', pname: 'Recharge' },
    { Id: 'Other', pname: 'Other' },
    { Id: 'Casual', pname: 'Casual' },
    { Id: 'Cloth', pname: 'Cloth' },
    { Id: 'Juice', pname: 'Juice' },
    { Id: 'PG Rent +', pname: 'PG Rent +' },
    // {Id:11,pname:'Breakfast'},
    // {Id:12,pname:'Breakfast'},
    // {Id:13,pname:'Breakfast'},
  ];
  export const PayFrom = [
    { Id: 1, pname: 'Paytm' },
    { Id: 2, pname: 'Phone Pay' },
    { Id: 3, pname: 'Google Pay' },
    { Id: 4, pname: 'Paytm Wallet' },
    { Id: 5, pname: 'Credit Card' },
    { Id: 6, pname: 'Debit Card' },
    { Id: 7, pname: 'UPI' },
    { Id: 8, pname: 'IMobile' },
    { Id: 9, pname: 'ICICI' },
    { Id: 10, pname: 'Amazon Pay' },
    { Id: 11, pname: 'Cash' },
    // {Id:12,pname:'Breakfast'},
    // {Id:13,pname:'Breakfast'},
  ];
  export const PayFromString = [
    { Id: 'Paytm', pname: 'Paytm' },
    { Id: 'Phone Pay', pname: 'Phone Pay' },
    { Id: 'Google Pay' , pname: 'Google Pay' },
    { Id: 'Paytm Wallet', pname: 'Paytm Wallet' },
    { Id: 'Credit Card', pname: 'Credit Card' },
    { Id: 'Debit Card', pname: 'Debit Card' },
    { Id: 'UPI', pname: 'UPI' },
    { Id: 'IMobile', pname: 'IMobile' },
    { Id: 'ICICI', pname: 'ICICI' },
    { Id: 'Amazon Pay', pname: 'Amazon Pay' },
    { Id: 'Cash', pname: 'Cash' },
    
  ];



  export const MonthName = [
    { Id: 1, pname: 'January' },
    { Id: 2, pname: 'February' },
    { Id: 3, pname: 'March' },
    { Id: 4, pname: 'April' },
    { Id: 5, pname: 'May' },
    { Id: 6, pname: 'June' },
    { Id: 7, pname: 'July' },
    { Id: 8, pname: 'August' },
    { Id: 9, pname: 'September' },
    { Id: 10, pname: 'October' },
    { Id: 11, pname: 'November' },
    { Id: 12, pname: 'December' },
  ];
  export const YearS = [
    { y: 2021 },
    { y: 2022 },
    { y: 2023 },
    { y: 2024 },
    { y: 2025 },
    { y: 2026 },
  ];
  export const btnnumber = [
    { 1: 200 },
    // {btn:2},
    // {btn:3},
    // {btn:4},
    // {btn:5},
    // {btn:6},
    // {btn:7},
    // {btn:8},
    // {btn:9},
    // {btn:10},
    // {btn:11},
    // {btn:12},
    // {btn:13},
    // {btn:14},
    // {btn:15},
    // {btn:16},
    // {btn:17},
    // {btn:19},
    // {btn:20},
    // {btn:21},
    // {btn:22},
    // {btn:23},
    // {btn:24},
    // {btn:25},
    // {btn:26},
    // {btn:27},
    // {btn:28},
    // {btn:29},
    // {btn:30},
    // {btn:31},
  ]
  
 
  